### ISSUE TITLE
[Bug]: Game crashes

### ISSUE THREAD

**Issue by TheRealOnogen** [PC-Logix/OpenComputers#97]
## Description

Game crashes while loading mods

## Versions

- Minecraft version: 1.21.1
- Forge version: 21.1.250
- OpenComputers version: 1.9.4-5
- Java version: 21.0.2
- Modpack (if applicable): Custom

## Environment

- Operating system: Arch Linux
- Single-player or server: Doesn't even matter
- If server: dedicated or integrated, and server-side mod list:
- Other mods installed: Too many to list, you can see in log

## Steps to reproduce

1. Open the game
2. Game crashes

## Expected behavior

Game loads

## Actual behavior

Game crashes

## Logs and crash reports

https://pastebin.com/3G4V84Qg

## Additional information
Include anything else that may help: a minimal world or save, reproduction video,
screenshots, affected OpenComputers component(s), whether the issue started after
an update, and whether it still occurs with only the required dependencies installed.
-->

## Checklist

- [ ] I searched the existing issues for duplicates.
- [ ] I included the exact Minecraft, Forge, and OpenComputers versions.
- [ ] I included clear reproduction steps.
- [ ] I attached the relevant log/crash report or provided a full mclo.gs link.
- [ ] I removed private information from attached logs.
- [ ] I tested whether the issue occurs without unrelated mods, if practical.

**Comment by RobertCochran** [comment]
Log pins this down to being because of
```
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.item.TooltipFlag.shouldDisplayAllInformation()'
	at TRANSFORMER/opencomputers@/li.cil.oc.util.Tooltip$.showExtendedTooltip(Tooltip.scala:16) ~[opencomputers-1.9.4-dev.285.jar%23260!/:1.9.4-dev.285] {re:classloading}
```
something is maybe overriding vanilla behavior here?

**Comment by TheRealOnogen** [comment]
wait that's the wrong log, here's the new one

[crash-2026-09-11_19.59.53-client.txt](https://github.com/user-attachments/files/32125209/crash-2026-09-11_19.59.53-client.txt)

**Comment by RobertCochran** [comment]
This log says
```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: li/cil/oc/util/RarityExt
	at MC-BOOTSTRAP/fml_loader@4.0.42/net.neoforged.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29) ~[loader-4.0.42.jar%2389!/:4.0] {}
```

**Comment by TheRealOnogen** [comment]
yeah that's when i updated to 1.9.4-5

**Comment by CaitlynMainer** [comment]
Where did you get build 1.9.4-5?  It's not been approved anywhere yet.

**Comment by TheRealOnogen** [comment]
right here
https://github.com/PC-Logix/OpenComputers/actions/runs/34619948717

**Comment by CaitlynMainer** [comment]
The jar from that release correctly has
li/cil/oc/util/RarityExt.class
META-INF/enumextensions.json

As I would expect.  So it's not a case of the class just missing.

**Comment by CaitlynMainer** [comment]
<img width="1919" height="1150" alt="Image" src="https://github.com/user-attachments/assets/b7406706-a927-4777-8fee-0bef4d6ed1aa" />
I'm in game with no issue on 1.9.4-5 SO not sure what's causing your missing class, but it's something on your side.

**Comment by TheRealOnogen** [comment]
ok turns out i'm just dumb and i was not supposed to put the -sources and -api jars

**Comment by CaitlynMainer** [comment]
Yep, that'll do it.  Those are for addon developers.
